#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokeapiml-deployment
spec:
  selector:
    matchLabels:
      app: strokeapiml-server
  replicas: 1
  template:
    metadata:
      labels:
        app: strokeapiml-server
    spec:
      containers:
      - name: strokeapiml-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/frankisoft/strokeapiml:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: strokeapiml-service
  name: strokeapiml-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: strokeapiml-server
  type: LoadBalancer
